import React, { useState } from 'react';
import {
  Sparkles,
  Send,
  CalendarDays,
  CheckCircle2,
  Share2,
  Copy,
  Edit2,
  Image as ImageIcon,
  Check,
  Video,
  Mail,
  MessageSquare,
  DollarSign,
  Target
} from 'lucide-react';
import { useAppStore } from '../services/store';

interface CampaignAutopilotProps {
  onNavigateTab: (tab: any) => void;
}

export const CampaignAutopilot: React.FC<CampaignAutopilotProps> = ({ onNavigateTab }) => {
  const { state, addCampaign, createApprovalRequest } = useAppStore();

  const [promptInput, setPromptInput] = useState(
    'Create a Back-to-School laptop campaign for university students with a budget of USD 100.'
  );
  const [budgetUSD, setBudgetUSD] = useState(100);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedCampaign, setGeneratedCampaign] = useState<any>(null);
  const [activeContentTab, setActiveContentTab] = useState<'facebook' | 'instagram' | 'video' | 'creative'>('facebook');
  const [copiedText, setCopiedText] = useState(false);

  const isMM = state.language === 'my';

  const handleGenerateCampaign = async () => {
    if (!promptInput.trim()) return;
    setIsGenerating(true);

    try {
      const res = await fetch('/api/ai/campaign', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: promptInput,
          budgetUSD,
          orgName: state.currentOrg?.name,
          brandVoice: state.currentOrg?.toneOfVoice,
          productsContext: state.products.map(p => `${p.name} (${p.category}): ${p.priceMMK} MMK`).slice(0, 8).join('; '),
        }),
      });

      const data = await res.json();
      if (data.campaign) {
        setGeneratedCampaign(data.campaign);
      }
    } catch (e) {
      console.error('Error generating campaign:', e);
      // Fallback demo campaign
      setGeneratedCampaign(state.campaigns[0]);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleApproveAndSchedule = () => {
    if (!generatedCampaign) return;

    // Save to store
    const newCamp = addCampaign({
      title: generatedCampaign.title || 'Back-to-School Laptop Campaign',
      objective: generatedCampaign.objective || 'Drive student laptop sales',
      targetAudience: generatedCampaign.targetAudience || 'University students',
      budgetUSD,
      recommendedProductIds: ['prod_lap_lite', 'prod_lap_pro', 'prod_acc_mouse'],
      valueProposition: generatedCampaign.valueProposition || 'High performance student laptop bundles',
      offerDetails: 'Free Wireless Mouse & Backpack with Laptop Pro',
      channels: ['facebook', 'instagram', 'telegram'],
      content: generatedCampaign.content || {},
      creativeBrief: generatedCampaign.creativeBrief || {
        visualConcept: 'Student studying in cafe with laptop',
        brandColors: ['#2563eb', '#1e40af'],
        imagePrompt: 'A student using laptop in modern cafe',
        typographyGuide: 'Bold display headline',
        ctaText: 'Claim Discount',
        recommendedDimensions: '1080x1080',
      },
      hashtags: generatedCampaign.hashtags || ['#NovaTech', '#BackToSchool'],
      status: 'scheduled',
      startDate: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      endDate: new Date(Date.now() + 14 * 24 * 3600 * 1000).toISOString(),
      kpis: generatedCampaign.kpis || {
        expectedInquiries: 40,
        expectedOrders: 10,
        targetRevenueUSD: 7500,
      },
    });

    // Request owner approval
    createApprovalRequest({
      type: 'publish_campaign',
      title: `Approve Launch: ${newCamp.title}`,
      description: `Campaign generated by AI Autopilot targeting ${newCamp.targetAudience} with $${budgetUSD} budget.`,
      requestedBy: 'ai',
      requesterName: 'AI Campaign Autopilot',
      riskLevel: 'medium',
      payload: { campaignId: newCamp.id },
    });

    alert('Campaign strategy and copy generated & sent to Approval Center & Content Calendar!');
    onNavigateTab('calendar');
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedText(true);
    setTimeout(() => setCopiedText(false), 2000);
  };

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full neu-pill text-[#A98C63] text-xs font-bold mb-1">
            <Sparkles className="w-3.5 h-3.5 text-[#A98C63]" />
            <span>Core Differentiator</span>
          </div>
          <h2 className="text-xl font-bold text-[#222222] tracking-tight">{isMM ? 'AI ကမ်ပိန်း ရေးဆွဲသူ' : 'AI Campaign Autopilot'}</h2>
          <p className="text-xs text-slate-500">Transform natural language prompts into complete, multi-channel marketing campaigns</p>
        </div>
      </div>

      {/* Campaign Prompt Wizard Box */}
      <div className="neu-flat rounded-2xl p-6 shadow-sm space-y-4">
        <label className="block text-xs font-bold text-[#222222] uppercase tracking-wider">
          {isMM ? 'ကမ်ပိန်း အိုင်ဒီယာ ထည့်သွင်းပါ' : 'Describe Your Marketing Campaign Goal'}
        </label>

        <div className="flex flex-col sm:flex-row gap-3">
          <textarea
            value={promptInput}
            onChange={(e) => setPromptInput(e.target.value)}
            rows={2}
            placeholder="e.g. Create a Back-to-School laptop campaign for university students with a budget of USD 100."
            className="flex-1 neu-inset rounded-xl p-3 text-xs text-[#222222] placeholder-slate-400 focus:outline-none focus:ring-1 focus:ring-[#C5A880] leading-relaxed"
          />

          <div className="flex flex-col justify-between gap-2 shrink-0 sm:w-48">
            <div className="neu-inset p-2 rounded-xl flex items-center justify-between text-xs">
              <span className="text-slate-500 font-medium">Budget:</span>
              <div className="flex items-center font-bold text-[#A98C63]">
                $<input
                  type="number"
                  value={budgetUSD}
                  onChange={(e) => setBudgetUSD(parseInt(e.target.value) || 50)}
                  className="w-12 text-right bg-transparent focus:outline-none font-bold text-[#A98C63]"
                />
              </div>
            </div>

            <button
              onClick={handleGenerateCampaign}
              disabled={isGenerating}
              className="w-full neu-gold text-white font-bold py-3 px-4 rounded-xl shadow-md transition-all text-xs flex items-center justify-center gap-2 active:scale-95 disabled:opacity-50"
            >
              <Sparkles className="w-4 h-4 text-white animate-spin-slow" />
              <span>{isGenerating ? 'Generating Strategy...' : 'Generate Campaign'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Generated Campaign Output View */}
      {generatedCampaign && (
        <div className="neu-flat rounded-2xl p-6 shadow-md space-y-6 animate-fade-in">
          {/* Header Banner */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#EAE5DC] pb-4">
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-[#A98C63]">Generated Campaign Strategy</span>
              <h3 className="font-bold text-[#222222] text-lg">{generatedCampaign.title}</h3>
              <p className="text-xs text-slate-500 leading-relaxed">{generatedCampaign.objective}</p>
            </div>

            <button
              onClick={handleApproveAndSchedule}
              className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold px-5 py-2.5 rounded-xl shadow-md text-xs flex items-center justify-center gap-2 shrink-0"
            >
              <CheckCircle2 className="w-4 h-4 text-white" />
              <span>Approve & Schedule Campaign</span>
            </button>
          </div>

          {/* Strategy & KPI Highlights */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
            <div className="p-3 bg-[#FAF8F5] border border-[#EAE5DC] rounded-xl space-y-1">
              <span className="text-[10px] text-[#A98C63] font-bold uppercase">Target Audience</span>
              <p className="font-semibold text-[#222222]">{generatedCampaign.targetAudience}</p>
            </div>
            <div className="p-3 bg-[#FAF8F5] border border-[#EAE5DC] rounded-xl space-y-1">
              <span className="text-[10px] text-purple-700 font-bold uppercase">Value Proposition</span>
              <p className="font-semibold text-[#222222]">{generatedCampaign.valueProposition}</p>
            </div>
            <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl space-y-1">
              <span className="text-[10px] text-emerald-700 font-bold uppercase">Target Revenue KPI</span>
              <p className="font-bold text-emerald-800">${generatedCampaign.kpis?.targetRevenueUSD} USD ({generatedCampaign.kpis?.expectedOrders} Orders)</p>
            </div>
          </div>

          {/* Copy & Creative Tabs */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 border-b border-[#EAE5DC] text-xs overflow-x-auto">
              <button
                onClick={() => setActiveContentTab('facebook')}
                className={`pb-2.5 px-3 font-bold border-b-2 transition ${
                  activeContentTab === 'facebook' ? 'border-[#C5A880] text-[#A98C63]' : 'border-transparent text-slate-500 hover:text-[#222222]'
                }`}
              >
                Facebook Post
              </button>
              <button
                onClick={() => setActiveContentTab('instagram')}
                className={`pb-2.5 px-3 font-bold border-b-2 transition ${
                  activeContentTab === 'instagram' ? 'border-[#C5A880] text-[#A98C63]' : 'border-transparent text-slate-500 hover:text-[#222222]'
                }`}
              >
                Instagram Caption
              </button>
              <button
                onClick={() => setActiveContentTab('video')}
                className={`pb-2.5 px-3 font-bold border-b-2 transition ${
                  activeContentTab === 'video' ? 'border-[#C5A880] text-[#A98C63]' : 'border-transparent text-slate-500 hover:text-[#222222]'
                }`}
              >
                Reels/TikTok Script
              </button>
              <button
                onClick={() => setActiveContentTab('creative')}
                className={`pb-2.5 px-3 font-bold border-b-2 transition ${
                  activeContentTab === 'creative' ? 'border-[#C5A880] text-[#A98C63]' : 'border-transparent text-slate-500 hover:text-[#222222]'
                }`}
              >
                Creative Brief & Image Prompt
              </button>
            </div>

            {/* Tab Content Panels */}
            <div className="p-4 neu-inset rounded-xl text-xs space-y-3">
              {activeContentTab === 'facebook' && (
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-[#222222]">Facebook Ad Copy</span>
                    <button
                      onClick={() => copyToClipboard(generatedCampaign.content?.facebookCopy || '')}
                      className="text-[#A98C63] hover:underline flex items-center gap-1 text-[11px]"
                    >
                      {copiedText ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
                      <span>{copiedText ? 'Copied' : 'Copy Text'}</span>
                    </button>
                  </div>
                  <p className="text-[#222222] whitespace-pre-wrap leading-relaxed">{generatedCampaign.content?.facebookCopy}</p>
                </div>
              )}

              {activeContentTab === 'instagram' && (
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-[#222222]">Instagram Caption</span>
                    <button
                      onClick={() => copyToClipboard(generatedCampaign.content?.instagramCaption || '')}
                      className="text-[#A98C63] hover:underline flex items-center gap-1 text-[11px]"
                    >
                      <Copy className="w-3 h-3" /> Copy
                    </button>
                  </div>
                  <p className="text-[#222222] whitespace-pre-wrap leading-relaxed">{generatedCampaign.content?.instagramCaption}</p>
                </div>
              )}

              {activeContentTab === 'video' && (
                <div className="space-y-2">
                  <span className="font-bold text-[#222222]">Short Video Script (30 seconds)</span>
                  <p className="text-[#222222] whitespace-pre-wrap font-mono leading-relaxed neu-flat p-3 rounded-lg">
                    {generatedCampaign.content?.videoScript}
                  </p>
                </div>
              )}

              {activeContentTab === 'creative' && (
                <div className="space-y-3 text-slate-600">
                  <div>
                    <span className="font-bold text-[#222222] block mb-0.5">Visual Concept</span>
                    <p>{generatedCampaign.creativeBrief?.visualConcept}</p>
                  </div>
                  <div className="neu-flat p-3 rounded-lg space-y-1">
                    <span className="font-bold text-[#A98C63] text-[11px] block uppercase">AI Image Prompt for Gemini / Imagen</span>
                    <p className="font-mono text-[11px] text-[#222222]">{generatedCampaign.creativeBrief?.imagePrompt}</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
